# Generated by Django 3.2.5 on 2021-07-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='poll',
            new_name='question',
        ),
    ]
