# Generated by Django 3.2.5 on 2021-07-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Przedmioty',
            new_name='Przedmiot',
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena_text', models.CharField(max_length=128)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('przedmiot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dziennik.przedmiot')),
            ],
        ),
    ]
