# Generated by Django 3.2.5 on 2021-07-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0003_auto_20210729_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='ocena_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
    ]
