# Generated by Django 3.2.5 on 2021-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0004_auto_20210729_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nauczyciel',
            name='klasa',
        ),
        migrations.AddField(
            model_name='nauczyciel',
            name='klasa',
            field=models.ManyToManyField(to='dziennik.Klasa'),
        ),
    ]
