# Generated by Django 3.2.5 on 2021-07-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0005_auto_20210729_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='name',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=5),
        ),
    ]
