# Generated by Django 3.2.5 on 2021-08-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0006_alter_ocena_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='name',
            field=models.CharField(choices=[('1', '1'), ('1+', '1+'), ('2-', '2-'), ('2', '2'), ('2+', '2+'), ('3-', '3-'), ('3', '3'), ('3+', '3+'), ('4-', '4-'), ('4', '4'), ('4+', '4+'), ('5-', '5-'), ('5', '5'), ('5+', '5+'), ('6-', '6-'), ('6', '6')], max_length=4),
        ),
        migrations.RemoveField(
            model_name='przedmiot',
            name='klasa',
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='klasa',
            field=models.ManyToManyField(to='dziennik.Klasa'),
        ),
    ]
